### ISSUE TITLE
Add 4-byte Unicode support to Database for Showdown Usernames

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/CodenameIndigo#1]
See title. For Saph to fix.

**Comment by jdsaphir** [comment]
🤔

**Comment by jdsaphir** [comment]
Tried to change the database's and table's charset when it was really the fields' charset that was causing the issue... Should be solved.

**Comment by dylanpiera** [comment]
The database accepts them now, but it seems the API still doesn't. What did you change exactly?

**Comment by jdsaphir** [comment]
- Changed database's collation to utf8mb4-general-ci
- Changed table's collation to utf8mb4-general-ci
- Changed all fields' (except UUID) collation to utf8mb4-general-ci
- Tried UPDATEing a value with an emoji, worked.
